language: node_js
node_js:
- "0.10"

before_install: npm install -g grunt-cli
install: npm install

before_script:
  - npm install -g bower
  - bower install
  - grunt
  
#language: node_js
#node_js:
#- "0.10"
#- "0.11"

#before_install: npm install -g grunt-cli
#install: npm install

#matrix:
#  allow_failures:
#      - node_js: "0.11"
      
#before_script:
#  - npm install -g bower
#  - bower install
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - grunt
